services:
  - type: web
    name: playto-pay-web
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && python manage.py seed && gunicorn config.wsgi --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playto-pay-db
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: worker
    name: playto-pay-worker
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: C_FORCE_ROOT=1 celery -A config worker -l info
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playto-pay-db
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings

  - type: worker
    name: playto-pay-beat
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: C_FORCE_ROOT=1 celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: playto-pay-db
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings

databases:
  - name: playto-pay-db
    plan: free
