web: echo "DATABASE_URL=$DATABASE_URL REDIS_URL=$REDIS_URL" && python manage.py migrate && python manage.py seed && python manage.py collectstatic --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT
worker: C_FORCE_ROOT=1 celery -A config worker -l info
beat: C_FORCE_ROOT=1 celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
